app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/uploaddb
    username: postgres
    password: Abdelait12.
    pool-size: 30

application:
  jwt:
    secretKey: Abdelait12.mbistamiZamlKayfrejdaba
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 10
